# Generated by Django 5.0.6 on 2024-08-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='body',
        ),
    ]
