# Generated by Django 5.0.6 on 2024-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
