# Generated by Django 5.0.6 on 2024-10-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
