# Generated by Django 5.0.6 on 2024-10-12 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_skill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('answer', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Fulstack', 'Fulstack')], max_length=200)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
