# Generated by Django 5.0.6 on 2024-10-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Fulstack', 'Fulstack')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
