# Generated by Django 5.0.6 on 2024-11-13 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('answer', models.CharField(choices=[('Argentina', 'Argentina'), ('Brazil', 'Brazil'), ('Chile', 'Chile')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
