# Generated by Django 5.0.6 on 2024-11-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_country_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='answer',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('US', 'United States'), ('CA', 'Canada'), ('UY', 'Uruguay'), ('IT', 'Italy')], max_length=200),
        ),
    ]
