# Generated by Django 5.0.6 on 2024-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_country_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='mapped_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
