# Generated by Django 5.0.6 on 2024-12-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_message_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
