# Generated by Django 5.0.6 on 2024-12-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
    ]
